// src/app/data/products.ts
import { Product } from '../models/product.model';

export const products: Product[] = [
  { id: 1, name: 'Ryzen 5 5600X', brand: 'AMD', category: 'cpu', price: 200, image: '../cpu1.png', cores: 6, clockSpeed: '3.7', text: 'A powerful mid-range CPU suitable for gaming and productivity.' },
  { id: 2, name: 'Intel i5 12400', brand: 'Intel', category: 'cpu', price: 180, image: '../cpu2.png', cores: 6, clockSpeed: '2.5', text: 'An efficient CPU offering great performance for everyday tasks and gaming.' },
  {id:3, name:'Intel i7 12700K', brand:'Intel', category:'cpu', price:350, image:'../cpu3.png', cores:12, clockSpeed:'3.6', text: 'A high-performance CPU designed for gaming and intensive applications.'},
 {id:4, name:'Ryzen 7 5800X', brand:'AMD', category:'cpu', price:320, image:'../cpu4.png', cores:8, clockSpeed:'3.8', text: 'A robust CPU ideal for gaming and content creation.'},
   {id:5, name:'ryzen 9 5900X', brand:'AMD', category:'cpu', price:450, image:'../cpu5.png', cores:12, clockSpeed:'3.7', text: 'A top-tier CPU for gamers and professionals seeking high performance.'},
  { id: 6, name: 'GTX 1660', brand: 'NVIDIA', category: 'gpu', price: 250, image: '../gpu1.png',text : 'A budget-friendly GPU that delivers solid 1080p gaming performance.' },
  { id: 7, name: 'RTX 3060', brand: 'NVIDIA', category: 'gpu', price: 400, image: '../gpu2.png', text: 'A mid-range GPU offering excellent performance for 1080p and 1440p gaming.' },
  { id: 8, name: 'RX 6600', brand: 'AMD', category: 'gpu', price: 350, image: '../gpu3.png', text: 'A competitive GPU for smooth 1080p gaming experiences.' },
 { id: 9, name: 'RTX 4070', brand: 'NVIDIA', category: 'gpu', price: 600, image: '../gpu4.png', text: 'A high-end GPU designed for 1440p and 4K gaming with ray tracing capabilities.' },
  { id: 10, name: 'RX 7900', brand: 'AMD', category: 'gpu', price: 650, image: '../gpu5.png', text: 'A premium GPU delivering exceptional performance for high-resolution gaming.' },
{ id: 11, name: '16GB DDR4 RAM', brand: 'Corsair', category: 'ram', price: 80, image: '../.png', text: 'High-performance RAM for smooth multitasking and gaming.' },
  { id: 12, name: '32GB DDR4 RAM', brand: 'G.Skill', category: 'ram', price: 150, image: '../.png', text: 'Ample memory for demanding applications and future-proofing your system.'   },
  { id: 13, name: '16GB DDR5 RAM', brand: 'Kingston', category: 'ram', price: 120, image: '../.png', text: 'Next-generation RAM offering improved speed and efficiency.'   },
 { id: 14, name: '32GB DDR5 RAM', brand: 'Crucial', category: 'ram', price: 220, image: '../.png', text: 'High-capacity DDR5 RAM for cutting-edge performance and multitasking.' },
 { id: 15, name: 'Gigabyte X570 Aorus Elite', brand: 'Gigabyte', category: 'motherboard', price: 200, image: '../mb1.png', text: 'A reliable motherboard with robust features for AMD Ryzen processors.' },
    { id: 16, name: 'ASUS TUF Gaming B660M', brand: 'ASUS', category: 'motherboard', price: 180, image: '../mb2.png', text: 'A durable motherboard designed for Intel Alder Lake processors with gaming features.' },
    { id: 17, name: 'MSI B550 Tomahawk', brand: 'MSI', category: 'motherboard', price: 130, image: '../mb3.png', text: 'A feature-rich motherboard optimized for AMD Ryzen processors.' },
    { id: 18, name: 'Gigabyte Z690 Aorus Pro', brand: 'Gigabyte', category: 'motherboard', price: 250, image: '../mb4.png', text: 'A high-performance motherboard for Intel Alder Lake processors with advanced connectivity.' },
    { id: 19, name: 'ASUS Prime Z590-P', brand: 'ASUS', category: 'motherboard', price: 170, image: '../mb5.png', text: 'A versatile motherboard suitable for Intel 11th Gen processors with solid performance.' },
    { id: 20, name: 'MSI MAG B660M Mortar', brand: 'MSI', category: 'motherboard', price: 180, image: '../mb6.png', text: 'A compact motherboard offering great features for Intel Alder Lake processors.' },
    { id: 21, name: 'Gigabyte B550 Aorus Pro', brand: 'Gigabyte', category: 'motherboard', price: 140, image: '../mb7.png', text: 'A reliable motherboard designed for AMD Ryzen processors with gaming features.' },
    { id: 22, name: 'Cooler Master Hyper 212', brand: 'Cooler Master', category: 'cooler', price: 40, image: 'assets/images/hyper212.png', text: 'An affordable air cooler providing efficient cooling for a variety of CPUs.' },
    { id: 23, name: 'Noctua NH-D15', brand: 'Noctua', category: 'cooler', price: 90, image: 'assets/images/nhd15.png', text: 'A premium air cooler known for its exceptional cooling performance and low noise levels.' },
    { id: 24, name: 'be quiet! Dark Rock 4', brand: 'be quiet!', category: 'cooler', price: 80, image: 'assets/images/darkrock4.png', text: 'A silent air cooler that delivers excellent thermal performance for high-end CPUs.' },
    { id: 25, name: 'NZXT Kraken X63', brand: 'NZXT', category: 'cooler', price: 130, image: 'assets/images/x63.png', text: 'A high-performance liquid cooler with customizable RGB lighting and efficient cooling.' },
    { id: 26, name: 'Corsair H100i RGB', brand: 'Corsair', category: 'cooler', price: 120, image: 'assets/images/h100i.png', text: 'A reliable liquid cooler featuring RGB lighting and strong cooling capabilities for gaming PCs.' },
    { id: 27, name: 'DeepCool Assassin III', brand: 'DeepCool', category: 'cooler', price: 85, image: 'assets/images/assassin3.png', text: 'A powerful air cooler with dual-tower design for superior cooling performance.' },
    { id: 28, name: 'Logitech G502', brand: 'Logitech', category: 'mouse', price: 60, image: 'assets/images/g502.png', text: 'A versatile gaming mouse with customizable buttons and high-precision tracking.' },
    { id: 29, name: 'Razer DeathAdder V2', brand: 'Razer', category: 'mouse', price: 70, image: 'assets/images/deathadder.png', text: 'An ergonomic gaming mouse known for its accuracy and comfort during long gaming sessions.' },
    { id: 30, name: 'SteelSeries Rival 600', brand: 'SteelSeries', category: 'mouse', price: 80, image: 'assets/images/rival600.png', text: 'A high-performance gaming mouse with dual sensors for precise tracking and control.' },
    { id: 31, name: 'Corsair M65 RGB', brand: 'Corsair', category: 'mouse', price: 75, image: 'assets/images/m65.png', text: 'A durable gaming mouse with adjustable weights and high-accuracy sensor for competitive gaming.' },
    { id: 32, name: 'Logitech G Pro X', brand: 'Logitech', category: 'mouse', price: 90, image: 'assets/images/gprox.png', text: 'A professional-grade gaming mouse designed for esports athletes with exceptional performance.' },
    { id: 33, name: 'HyperX Cloud II', brand: 'HyperX', category: 'headset', price: 100, image: 'assets/images/cloud2.png', text: 'A comfortable gaming headset with excellent sound quality and a noise-cancelling microphone.' },
    { id: 34, name: 'SteelSeries Arctis 7', brand: 'SteelSeries', category: 'headset', price: 150, image: 'assets/images/arctis7.png', text: 'A wireless gaming headset offering immersive sound and a clear microphone for communication.' },
    { id: 35, name: 'Razer BlackShark V2', brand: 'Razer', category: 'headset', price: 120, image: 'assets/images/blackshark.png', text: 'A lightweight gaming headset with THX spatial audio and a detachable microphone for clear communication.' },
    { id: 36, name: 'Corsair Virtuoso', brand: 'Corsair', category: 'headset', price: 180, image: 'assets/images/virtuoso.png', text: 'A premium gaming headset with high-fidelity audio and a broadcast-grade microphone for superior sound quality.' },
    { id: 37, name: 'Logitech G935', brand: 'Logitech', category: 'headset', price: 160, image: 'assets/images/g935.png', text: 'A wireless gaming headset with DTS Headphone:X 2.0 surround sound and RGB lighting for an immersive gaming experience.' },
     { id: 38, name: 'Corsair K95 RGB', brand: 'Corsair', category: 'keyboard', price: 200, image: 'assets/images/k95.png',text: 'A high-end mechanical keyboard with customizable RGB lighting and dedicated macro keys for gaming.' },
    { id: 39, name: 'Razer BlackWidow V3', brand: 'Razer', category: 'keyboard', price: 150, image: 'assets/images/blackwidow.png', text: 'A durable mechanical keyboard with Razer Green switches and customizable RGB lighting for an enhanced gaming experience.' },
    { id: 40, name: 'Logitech G915', brand: 'Logitech', category: 'keyboard', price: 250, image: 'assets/images/g915.png', text: 'A sleek wireless mechanical keyboard with low-profile GL switches and RGB lighting for gamers on the go.' },
    { id: 41, name: 'SteelSeries Apex Pro', brand: 'SteelSeries', category: 'keyboard', price: 180, image: 'assets/images/apexpro.png', text: 'A customizable mechanical keyboard with adjustable actuation switches and vibrant RGB lighting for competitive gaming.' },
    { id: 42, name: 'HyperX Alloy Elite 2', brand: 'HyperX', category: 'keyboard', price: 160, image: 'assets/images/alloyelite2.png', text: 'A solid mechanical keyboard with dynamic RGB lighting and dedicated media controls for an immersive gaming experience.' },
     { id: 43, name: 'SteelSeries QcK', brand: 'SteelSeries', category: 'mousepad', price: 20, image: 'assets/images/qck.png', text: 'A high-quality mousepad with a smooth surface for precise mouse movements and control.' },
    { id: 44, name: 'Razer Goliathus', brand: 'Razer', category: 'mousepad', price: 25, image: 'assets/images/goliathus.png', text: 'A durable mousepad with a textured surface for enhanced accuracy and speed during gaming sessions.' },
    { id: 45, name: 'Corsair MM300', brand: 'Corsair', category: 'mousepad', price: 30, image: 'assets/images/mm300.png', text: 'A large mousepad with a cloth surface for comfortable and precise mouse control.' },
    { id: 46, name: 'Logitech G640', brand: 'Logitech', category: 'mousepad', price: 28, image: 'assets/images/g640.png', text: 'A gaming mousepad with a low-friction surface for smooth and accurate mouse movements.' },
    { id: 47, name: 'HyperX Fury S', brand: 'HyperX', category: 'mousepad', price: 22, image: 'assets/images/furys.png', text: 'A comfortable mousepad with a soft cloth surface for enhanced gaming performance.' },
      { id: 33, name: 'HyperX Cloud II', brand: 'HyperX', category: 'headset', price: 100, image: 'assets/images/cloud2.png', text: 'A comfortable gaming headset with excellent sound quality and a noise-cancelling microphone.' },
    { id: 34, name: 'SteelSeries Arctis 7', brand: 'SteelSeries', category: 'headset', price: 150, image: 'assets/images/arctis7.png', text: 'A wireless gaming headset offering immersive sound and a clear microphone for communication.' },
    { id: 35, name: 'Razer BlackShark V2', brand: 'Razer', category: 'headset', price: 120, image: 'assets/images/blackshark.png', text: 'A lightweight gaming headset with THX spatial audio and a detachable microphone for clear communication.' },
    { id: 36, name: 'Corsair Virtuoso', brand: 'Corsair', category: 'headset', price: 180, image: 'assets/images/virtuoso.png', text: 'A premium gaming headset with high-fidelity audio and a broadcast-grade microphone for superior sound quality.' },
    { id: 37, name: 'Logitech G935', brand: 'Logitech', category: 'headset', price: 160, image: 'assets/images/g935.png',text: 'A wireless gaming headset with DTS Headphone:X 2.0 surround sound and RGB lighting for an immersive gaming experience.' },
    {id:38, name:'Condenser Mic', brand:'Blue', category:'mic', price:120, image:'../mic1.png', text: 'A high-quality condenser microphone ideal for streaming and recording.'},
    {id:39, name:'Dynamic Mic', brand:'Shure', category:'mic', price:100, image:'../mic2.png', text: 'A durable dynamic microphone perfect for live performances and podcasting.'},
    {id:40, name:'USB Mic', brand:'Razer', category:'mic', price:80, image:'../mic3.png', text: 'A convenient USB microphone suitable for gaming and online communication.'},
    {id:41, name:'Gaming Mic', brand:'HyperX', category:'mic', price:90, image:'../mic4.png', text: 'A gaming microphone designed for clear voice capture during gameplay.'},
    {id:42, name:'Podcast Mic', brand:'Audio-Technica', category:'mic', price:110, image:'../mic5.png', text: 'A professional microphone tailored for podcasting and voice-over work.'},
  ]

